export { Home } from './Home';
export { About } from './About';
export { Services } from './Services';
export { Contact } from './Contact';
export { default as Register } from '../components/Register';
export { Games } from './Games';
export { Community } from './Community';
export { Support } from './Support';
export { default as Friends } from './Friends';
export { default as Groups } from './Groups';
export { default as Events } from './Events';
export { default as Memories } from './Memories';
export { default as Saved } from './Saved';
export { default as Watch } from './Watch';