export { Home } from './Home';
export { About } from './About';
export { Services } from './Services';
export { Contact } from './Contact';
export { default as Register } from '../components/Register';
export { Games } from './Games';
export { Community } from './Community';
export { Support } from './Support';
export { default as Watch } from './Watch';
export { default as MyGames } from './MyGames';
export { default as DiscoverGames } from './DiscoverGames';
export { default as GameChallenges } from './GameChallenges';
export { default as Leaderboards } from './Leaderboards';
export { default as GameTournaments } from './GameTournaments';
export { default as GameCommunities } from './GameCommunities';
export { default as GlobalChat } from './GlobalChat';
export { default as GameCollectibles } from './GameCollectibles';